name: Build
on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    # Install
    - name: Install
      id: install
      run: npm install
    # Build
    - name: Build
      id: build
      run: npm run build
